name: Build Wheel

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools cython numpy

    - name: Build Wheel
      run: |
        python setup.py bdist_wheel

    - name: Upload Wheel
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/*.whl

    - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

    - name: Publish package to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m pip install --upgrade twine
        twine upload dist/*
